### ISSUE TITLE
Milestone 04 ready for review

### ISSUE THREAD

**Issue by jcoop1219** [jcoop1219/BME590L_Lightbulb#13]
Will also assign to Matt and Brinnae after they accept my invite as collaborators

**Comment by mlp6** [comment]
@jcoop1219 you don't seem to like sleep...

**Comment by mlp6** [comment]
Let's also add @ericsrichardson

**Comment by jcoop1219** [comment]
See minor updates & notes in release v0.2.1

**Comment by jcoop1219** [comment]
See newest updates in release v0.2.3

**Comment by sphaerobolus** [comment]
I don't think you need ground planes top and bottom. Pick one. 

I understand D1, though my opinion is that you don't need it. D1's existence implies you might not trust the voltage regulator. If you don't trust the regulator, get a better one. 

I'm not sure I understand D4, nor the use of an analog pin as a switch input.

**Comment by jcoop1219** [comment]
> I don't think you need ground planes top and bottom. Pick one.
> 
> I understand D1, though my opinion is that you don't need it. D1's existence implies you might not trust the voltage regulator. If you don't trust the regulator, get a better one.
> 
> I'm not sure I understand D4, nor the use of an analog pin as a switch input.

1. Is there any drawback to having 2 ground planes? I figured having a second ground plane could only help with insulating the circuit from external noise.
2. D1 is really there for the purposes of testing the circuit (like, when building out on breadboard). Using it to make sure I'm not discharging any static electricity >5V from my clothing to the Arduino. I'll remove D1 from the PCB.
3. I'm using this analog input as a battery voltage tester (to see how much juice is left in the battery). Ideally what's going into this input should never be above 4.5V (9V battery divided by 2 via voltage divider). D4 ensures this voltage won't go above 5.1V and I won't fry the Arduino.

**Comment by jcoop1219** [comment]
@sphaerobolus please see my comment above in response to your questions

**Comment by sphaerobolus** [comment]
In your case I think the added plane will merely be redundant. In some cases it can be problematic. It's not doing you much good. The positive effects do not add linearly. 

Ah, now I understand the analog input. In that case, I'm on board. Carry on.

**Comment by jcoop1219** [comment]
Thanks! I'll go ahead and remove the bottom layer ground plane, as well as remove D1 per the discussion above.
