### ISSUE TITLE
Milestone 05 ready for review

### ISSUE THREAD

**Issue by jcoop1219** [jcoop1219/BME590L_Lightbulb#21]
See latest release notes for [v0.3.0](https://github.com/jcoop1219/BME590L_Lightbulb/releases/tag/v0.3.0)

**Comment by mlp6** [comment]
@jcoop1219 how do your top and bottom secure to one another?  There also seem to be a lack of internal mounting points for the board(s), battery, etc.

**Comment by mlp6** [comment]
Noticed you still have some open Issues that will address some of these things.

**Comment by jcoop1219** [comment]
These issues (attachment of top to bottom, battery attachment, PCB) all addressed newest release [v0.3.1](https://github.com/jcoop1219/BME590L_Lightbulb/releases/tag/v0.3.1)

**Comment by mlp6** [comment]
Impressive!

**Comment by jcoop1219** [comment]
Thanks! Do you think I'm good to proceed with printing this?

**Comment by mlp6** [comment]
I think so... but there is no substitute for evaluating it in tangible form (for me).
